### ISSUE TITLE
Miss webgl support on the provided firefox browser from travis-ci

### ISSUE THREAD

**Issue by Danielhu229** [UniqueStudio/CanvasToy#2]
Travis-ci don't support webgl on the provided firefox browser

So far, I 've tried [headless gl](https://github.com/stackgl/headless-gl), but it build failed on the ubuntu linux , see [the build](https://travis-ci.org/UniqueStudio/CanvasToy/builds/159132530) 

**I'm looking for help if anyone knows another continues-integration solution, help  #wanted!**

**Comment by denghongcai** [comment]
https://github.com/stackgl/headless-gl#how-can-i-use-headless-gl-with-a-continuous-integration-service

**Comment by Danielhu229** [comment]
Thanks! the problem solved by install missing dependency by apt
